### ISSUE TITLE
ixbrl-reporter config-corptax.yaml report ixbrl > ct.html Does not work

### ISSUE THREAD

**Issue by winston0410** [cybermaggedon/ixbrl-reporter#7]
I tried to follow the tutorial, and run `ixbrl-reporter config-corptax.yaml report ixbrl > ct.html`. But I ended up with the following errors. Did I make any mistake, or is it an issue for the programe?

```sh
venv ❯ ixbrl-reporter config-corptax.yaml report ixbrl > ct.html
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Account.slots' will copy column accounts.guid to column slots.obj_guid, which conflicts with relationship(s): 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots"' to the 'Account.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Price.slots' will copy column prices.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots"' to the 'Price.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Commodity.slots' will copy column commodities.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots"' to the 'Commodity.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Split.slots' will copy column splits.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots"' to the 'Split.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Transaction.slots' will copy column transactions.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots"' to the 'Transaction.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'ScheduledTransaction.slots' will copy column schedxactions.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots"' to the 'ScheduledTransaction.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Lot.slots' will copy column lots.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots"' to the 'Lot.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Customer.slots' will copy column customers.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Customer.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Employee.slots' will copy column employees.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Employee.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Vendor.slots' will copy column vendors.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Vendor.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Billterm.slots' will copy column billterms.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid), 'Vendor.slots' (copies vendors.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Billterm.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Entry.slots' will copy column entries.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Billterm.slots' (copies billterms.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid), 'Vendor.slots' (copies vendors.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Entry.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Invoice.slots' will copy column invoices.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Billterm.slots' (copies billterms.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Entry.slots' (copies entries.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid), 'Vendor.slots' (copies vendors.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Invoice.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Job.slots' will copy column jobs.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Billterm.slots' (copies billterms.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Entry.slots' (copies entries.guid to slots.obj_guid), 'Invoice.slots' (copies invoices.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid), 'Vendor.slots' (copies vendors.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Job.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Order.slots' will copy column orders.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Billterm.slots' (copies billterms.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Entry.slots' (copies entries.guid to slots.obj_guid), 'Invoice.slots' (copies invoices.guid to slots.obj_guid), 'Job.slots' (copies jobs.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid), 'Vendor.slots' (copies vendors.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Order.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Taxtable.slots' will copy column taxtables.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Billterm.slots' (copies billterms.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Entry.slots' (copies entries.guid to slots.obj_guid), 'Invoice.slots' (copies invoices.guid to slots.obj_guid), 'Job.slots' (copies jobs.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Order.slots' (copies orders.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid), 'Vendor.slots' (copies vendors.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Taxtable.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Book.slots' will copy column books.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Billterm.slots' (copies billterms.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Entry.slots' (copies entries.guid to slots.obj_guid), 'Invoice.slots' (copies invoices.guid to slots.obj_guid), 'Job.slots' (copies jobs.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Order.slots' (copies orders.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Taxtable.slots' (copies taxtables.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid), 'Vendor.slots' (copies vendors.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Book.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Budget.recurrence' will copy column budgets.guid to column recurrences.obj_guid, which conflicts with relationship(s): 'ScheduledTransaction.recurrence' (copies schedxactions.guid to recurrences.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="recurrence"' to the 'Budget.recurrence' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/core/session.py:442: SAWarning: relationship 'Budget.slots' will copy column budgets.guid to column slots.obj_guid, which conflicts with relationship(s): 'Account.slots' (copies accounts.guid to slots.obj_guid), 'Billterm.slots' (copies billterms.guid to slots.obj_guid), 'Book.slots' (copies books.guid to slots.obj_guid), 'Commodity.slots' (copies commodities.guid to slots.obj_guid), 'Customer.slots' (copies customers.guid to slots.obj_guid), 'Employee.slots' (copies employees.guid to slots.obj_guid), 'Entry.slots' (copies entries.guid to slots.obj_guid), 'Invoice.slots' (copies invoices.guid to slots.obj_guid), 'Job.slots' (copies jobs.guid to slots.obj_guid), 'Lot.slots' (copies lots.guid to slots.obj_guid), 'Order.slots' (copies orders.guid to slots.obj_guid), 'Price.slots' (copies prices.guid to slots.obj_guid), 'ScheduledTransaction.slots' (copies schedxactions.guid to slots.obj_guid), 'Slot.parent' (copies slots.guid_val to slots.obj_guid), 'SlotFrame.slots' (copies slots.guid_val to slots.obj_guid), 'Split.slots' (copies splits.guid to slots.obj_guid), 'Taxtable.slots' (copies taxtables.guid to slots.obj_guid), 'Transaction.slots' (copies transactions.guid to slots.obj_guid), 'Vendor.slots' (copies vendors.guid to slots.obj_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="parent,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots,slots"' to the 'Budget.slots' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for v in s.query(Version).all()
/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/piecash/business/person.py:152: SAWarning: relationship 'Vendor.jobs' will copy column vendors.guid to column jobs.owner_guid, which conflicts with relationship(s): 'Customer.jobs' (copies customers.guid to jobs.owner_guid). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="jobs"' to the 'Vendor.jobs' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  cls.jobs = relation('Job',
Exception: Config value metadata.tax.rnd-claim-notification-submitted not known
Traceback (most recent call last):
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/bin/ixbrl-reporter", line 51, in <module>
    raise e
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/bin/ixbrl-reporter", line 33, in <module>
    elt.to_ixbrl(tx, sys.stdout)
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/basic_element.py", line 207, in to_ixbrl
    html = self.to_ixbrl_tree(taxonomy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/basic_element.py", line 182, in to_ixbrl_tree
    elts = self.to_ixbrl_elt(self, taxonomy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/composite.py", line 39, in to_ixbrl_elt
    elt = v.to_ixbrl_elt(par, taxonomy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/page.py", line 44, in to_ixbrl_elt
    sub = v.to_ixbrl_elt(par, taxonomy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/fact_table.py", line 71, in to_ixbrl_elt
    datum = self.data.to_datum(v, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/data_source.py", line 180, in to_datum
    value = self.get_config_bool(defn.get("key"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/data_source.py", line 162, in get_config_bool
    return self.cfg.get_bool(key, deflt, mandatory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/config.py", line 126, in get_bool
    val = self.get(key, dflt, mandatory)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Desktop/ixbrl-reporter/venv/lib/python3.12/site-packages/ixbrl_reporter/config.py", line 117, in get
    raise RuntimeError("Config value %s not known" % key)
RuntimeError: Config value metadata.tax.rnd-claim-notification-submitted not known
```

**Comment by winston0410** [comment]
So the issue is field 656 and 657 is not known. I wonder if it is checked against an API or some data source when it run?
https://github.com/cybermaggedon/ixbrl-reporter/blob/e67b120e0989767e5ee9a7672a2f592cfad78467/report/hmrc/corp-tax.yaml#L739

**Comment by cybermaggedon** [comment]
Hi, you should try adding this... to your metadata file...

```
  rnd-additional-notification-submitted: false
  rnd-claim-notification-submitted: false

```
